config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root 'index', controller: :homepage

  resources :taverns, only: %i[show] do
    resources :tables, only: %i[show], controller: :tavern_tables do
      resources :messages, only: %i[create], controller: :tavern_table_messages
    end
  end

  resources :sessions, only: %i[new create destroy]
end

app/models/tavern.rb
class Tavern < ApplicationRecord
  belongs_to :creator, class_name: 'UserAccount'

  has_many :tavern_tables
  has_many :tavern_accounts

  validates :name, presence: true
end

app/models/tavern_table.rb
class TavernTable < ApplicationRecord
  enum :variant, { text: 0, voice: 1 }
  belongs_to :tavern

  has_many :tavern_table_messages

  validates :name, presence: true
end

app/controllers/taverns_controller.rb
class TavernsController < ApplicationController
  before_action :set_taverns
  before_action :set_tavern, only: %i[show]

  def show; end

  private

  def set_tavern
    @tavern = @taverns.find(params[:id])
  end

  def set_taverns
    @taverns = @current_user.taverns
  end
end

app/views/taverns/show.html.erb
<%= render partial: 'application/navbar', locals: { taverns: @taverns } %>

<div class="grid grid-cols-12 h-full w-full">
  <div class="flex flex-col justify-between gap-2 col-span-3 bg-primary-800 overflow-scroll scrollbar-hidden h-full">
    <div class="sticky top-0 p-4 bg-primary-800 border-b border-primary-900/50">
      <h1 class="text-2xl text-primary-50"><%= @tavern.name %></h1>
    </div>
    <div class="flex flex-col gap-2 h-full">
      <% @tavern.tavern_tables.each do |tavern_table| %>
        <div class="flex">
          <%= link_to "# #{tavern_table.name}", tavern_table_path(@tavern, tavern_table), class: 'px-4 text-primary-50 w-full', data: { turbo_stream: true } %>
        </div>
      <% end %>
    </div>
    <div class="p-2 bg-primary-800 border-t border-primary-900/50">
      <%= render partial: 'accounts/card_small', locals: { account: @current_user } %>
    </div>
  </div>
  <%= render partial: 'tavern_tables/content', locals: { tavern: @tavern, tavern_table: @tavern.tavern_tables.first } %>
</div>

<%#<%= link_to 'Logout', session_path(@current_user), data: { turbo_method: :delete } %>