config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root 'index', controller: :homepage

  resources :taverns, only: %i[show] do
    resources :tables, only: %i[show], controller: :tavern_tables do
      resources :messages, only: %i[create], controller: :tavern_table_messages
    end
  end

  resources :sessions, only: %i[new create destroy]
end

app/controllers/tavern_tables_controller.rb
class TavernTablesController < ApplicationController
  before_action :set_tavern
  before_action :set_tavern_table, only: %i[show]

  def show; end

  private

  def set_tavern_table
    @tavern_table = @tavern.tavern_tables.find(params[:id])
  end

  def set_tavern
    @tavern = @current_user.taverns.find(params[:tavern_id])
  end
end

app/views/tavern_tables/_content.html.erb
<%= turbo_frame_tag :tavern_table, class: 'grid grid-cols-3 col-span-9 max-h-screen' do %>
  <div class="flex flex-col col-span-2 bg-primary-700 max-h-screen">
    <%= turbo_stream_from tavern_table, :tavern_table_messages %>
    <div class="sticky top-0 p-4 bg-primary-800 border-x border-x-primary-900/50 border-b border-b-primary-900">
      <h2 class="text-2xl text-primary-50"># <%= tavern_table.name %></h1>
    </div>
    <%= turbo_frame_tag :tavern_table_messages, class: 'flex flex-col-reverse h-full overflow-scroll scrollbar-hidden' do %>
      <% tavern_table.tavern_table_messages.order(id: :desc).each do |tavern_table_message| %>
        <%= render partial: 'tavern_table_messages/message', locals: { tavern_table_message: } %>
      <% end %>
    <% end %>
    <div class="sticky bottom-0 p-2 bg-primary-700">
      <%= form_with url: tavern_table_messages_path(tavern, tavern_table), scope: :tavern_table_message do |form| %>
        <%= form.text_field :content, placeholder: "Chat in ##{tavern_table.name}", class: 'text-primary-50 placeholder:text-primary-500 p-5 rounded-lg bg-primary-900 w-full' %>
      <% end %>
    </div>
  </div>
  <div class="flex flex-col gap-2 p-2 bg-primary-800 h-full overflow-scroll scrollbar-hidden">
    <% tavern.tavern_accounts.each do |tavern_account| %>
      <%= render partial: 'accounts/card_small', locals: { account: tavern_account.account } %>
    <% end %>
  </div>
<% end %>

app/views/tavern_tables/show.html.erb
<%= render partial: 'content', locals: { tavern: @tavern, tavern_table: @tavern_table } %>

app/views/tavern_tables/show.turbo_stream.erb
<%= turbo_stream.replace 'tavern_table', partial: 'content', locals: { tavern: @tavern, tavern_table: @tavern_table } %>