config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root 'index', controller: :homepage

  resources :taverns, only: %i[show] do
    resources :tables, only: %i[show], controller: :tavern_tables do
      resources :messages, only: %i[create], controller: :tavern_table_messages
    end
  end

  resources :sessions, only: %i[new create destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticated?

  private

  def authenticated?
    return redirect_to new_session_path if session[:current_user_id].blank?

    @current_user = UserAccount.find(session[:current_user_id])
  rescue ActiveRecord::RecordNotFound => error
    return redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<div class="flex flex-col gap-1 p-2 h-full min-w-fit bg-primary-900 overflow-scroll scrollbar-hidden">
  <%= link_to root_path, class: 'flex justify-center items-center p-1 bg-primary-800 rounded-lg' do %>
    <%= lucide_icon('home', class: 'bg-primary-900 rounded-lg text-white p-2', size: '48') %>
  <% end %>
  <hr class="border-primary-800" />
  <% taverns.each do |tavern| %>
    <%= link_to tavern_path(tavern), class: 'flex justify-center items-center p-1 bg-primary-800 rounded-lg backdrop-blur-md' do %>
      <div class="bg-primary-900 rounded-lg h-12 w-12"></div>
    <% end %>
  <% end %>
</div>